platform:
  - x64

cache:
  - node_modules

environment:
  GH_TOKEN:
    secure: X4+nWJ2UjDsok24dyGMoUZwDjrPzDFYxxbCcp9k7XZtctGgHBH6n8vH1id2gVQal

install:
  - ps: Install-Product node 8 x64
  - yarn install

build_script:
  - yarn assets
  - yarn dist

matrix:
  fast_finish: true
build: off
version: '{build}'
shallow_clone: true
clone_depth: 1
