platform:
  - x64

branches:
  only:
    - master

cache:
  - node_modules

# BUILD

image: Visual Studio 2015

install:
  - ps: Install-Product node 8 x64
  - yarn install

build_script:
  - yarn assets
  - yarn dist

matrix:
  fast_finish: true
version: '{build}'
shallow_clone: true
clone_depth: 1


artifacts:

  - path: 'dist\*.exe'

# deploy:
#   - provider: GitHub
#     artifact: /dist\\.*\.exe/
#     draft: true
#     prerelease: false
